version: '2.3'
services:
  bot:
    image: ghcr.io/floatingmilkshake/mechanicalmilkshake
    env_file:
      - .env
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always
